### PR TITLE
Add EXTNAME to summary files

### LINKED ISSUE #26: Add EXTNAME to HDUs in GFA summary files
Currently GFA summary files do not have `EXTNAME` set for any HDU. This conflicts with requirements of the DESI data model among other things.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR closes #26. This is a very simple PR, but I'll open it up for review anyway. The names have been chosen to match desihub/desidatamodel#202.

### CODE REVIEW

**Comment by weaverba137** [comment]
PS, let's test this in actual operations before merging.

**Review by sbailey — APPROVED** [review]

**Comment by weaverba137** [comment]
@sbailey, this is very strange: in actual operations, the `EXTNAME` is still not being set in files generated in the last week or so. I can tell from the scron logs that this branch is being used when the summary file is created, because of some small changes I made to the log messages. Is it possible that another process is overwriting the summary files?

**Comment by weaverba137** [comment]
Oy vey. I applied changes to `_write_many_nights()` but it's actually `_append_many_nights()` that writes the file. Totally redundant code in two different places. At least I can fix that easily.

**Comment by weaverba137** [comment]
`EXTNAME` and HDU checksum headers are now appearing as of night 20241202. Merging momentarily.

**Pull request merged**
